-- Create "todos" table
CREATE TABLE "todos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "description" text NULL, "completed" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "todo_completed" to table: "todos"
CREATE INDEX "todo_completed" ON "todos" ("completed");
-- Create index "todo_created_at" to table: "todos"
CREATE INDEX "todo_created_at" ON "todos" ("created_at");
